spring:
  datasource:
    url: jdbc:h2:mem:comp
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate.jdbc.time_zone: UTC